#this is a playbook for the second VM in lab 10


- name: setup Mysql with db and remote login
  become: yes
  hosts: all
  tasks:
    - name: Installing Mysql and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: creating mysql user
      mysql_user:
        name: "vagrant"
        password: "vagrant"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: Creates database for opencart
      mysql_db:
        name: "opencart"
        state: present
        login_user: vagrant
        login_password: "vagrant"
      tags: [ mysql ]

    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
